### ISSUE TITLE
Path Issues on Raspi

### ISSUE THREAD

**Issue by mahaamesha** [mahaamesha/fish-length-opencv#18]
Release code v2.0.0 is work just fine. But in raspi, there are path issues.
```
$ python run.py

Use segmentation config_0............ Done

[ WARN:0@48.705] global /tmp/pip-wheel-efxaz4j7/opencv-python_bedc0fac27944da0921e079da44d32bf/opencv/modules/imgcodecs/src/loadsave.cpp (239) findDecoder imread_('imgtest/lele.jpg'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "/home/ma-pi/_myProjects/iot_aquaculture/src/fish-length-opencv/run.py", line 3, in <module>
    from src.mafunction import add_encode_resultjson, clear_json_file, update_files_from_resultjson, validate_resultjson
  File "/home/ma-pi/_myProjects/iot_aquaculture/src/fish-length-opencv/src/mafunction.py", line 10, in <module>
    import src.segmentation as s
  File "/home/ma-pi/_myProjects/iot_aquaculture/src/fish-length-opencv/src/segmentation.py", line 39, in <module>
    cvt = cv.cvtColor(image, cv.COLOR_BGR2GRAY)     # Convert object color to GRAY
cv2.error: OpenCV(4.5.5) /tmp/pip-wheel-efxaz4j7/opencv-python_bedc0fac27944da0921e079da44d32bf/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

So, I need to get relative path, then edit all path in every file.

**Comment by mahaamesha** [comment]
I clear path issues by change it to relative path. For example

```python
import os
working_path = os.path.dirname(__file__)
path = os.path.join(working_path, '../tmp/result.json')
```

**Comment by mahaamesha** [comment]
That's work when I have a hierarchy like this:
```
iot_aquaculture/
    src/
        fish_length_opencv/
            src/
                mafunction.py
            run.py
    tmp/
    imgcv/
```

**Comment by mahaamesha** [comment]
> This error appear again. I think it because I'am not yet editing the `command line` in `run.py`

I'am stuck with that. I have alternative to clone the `fish-length-opencv` into `_myProjects`, instead of `iot_aquaculture/src/`

Don't forget to edit `camera.py`

**Comment by mahaamesha** [comment]
Error on the comment before, [**18#issuecomment**](https://github.com/mahaamesha/fish-length-opencv/issues/18#issuecomment-1134585779)

> This error appear again. I think it because I'am not yet editing the `command line` in `run.py`
> 
> ```
> $ python -u "~\iot_aquaculture\src\fish_length_opencv\run.py"
> 
> Use segmentation config_0............ Done
> 
> [ WARN:0@1.042] global D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('imgtest/lele.jpg'): can't open/read file: check file path/integrity
> Traceback (most recent call last):
>   File "d:\My_Project\IoT_aquaculture\src\fish_length_opencv\run.py", line 2, in <module>
>     from src.mafunction import get_path_relative_to_src, add_encode_resultjson, clear_json_file, update_files_from_resultjson, validate_resultjson, print_final_result
>   File "d:\My_Project\IoT_aquaculture\src\fish_length_opencv\src\mafunction.py", line 10, in <module>
>     import src.segmentation as s
>   File "d:\My_Project\IoT_aquaculture\src\fish_length_opencv\src\segmentation.py", line 41, in <module>
>     cvt = cv.cvtColor(image, cv.COLOR_BGR2GRAY)     # Convert object color to GRAY
> cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'
> ```
> 
> 
> Check by click this [`run.py`](https://github.com/mahaamesha/fish-length-opencv/blob/master/run.py)
> 
> ```python
> os.system('cmd /c "python main.py --image img/%s"' %f)
> ```

<br/>

The problem is in `cv.imread(path)`. It can't handle long path. I replace it using `pyplot` module. Check [segmentation.py](https://github.com/mahaamesha/fish-length-opencv/blob/master/src/segmentation.py)
```python
plt.imread(__longpath__)
```
